insert into series (title,author_id,subgenre_id) values ('lotr',1,1);
insert into series (title,author_id,subgenre_id) values ('lotr',1,1);
insert into books (title, year, series_id) values ('hello',1982,1);
insert into books (title, year, series_id) values ('hello',1982,1);
insert into books (title, year, series_id) values ('hello',1982,1);
insert into books (title, year, series_id) values ('hello',1982,1);
insert into books (title, year, series_id) values ('hello',1982,1);
insert into books (title, year, series_id) values ('hello',1982,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into characters (name, motto, species, author_id, series_id) values ('chance','woof','doggo',1,1);
insert into subgenres (name) values ('dogfiction');
insert into subgenres (name) values ('dogfiction');
insert into authors (name) values ('Steve');
insert into authors (name) values ('Steve');
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
insert into character_books (character_id,book_id) values (1,1);
